language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t scottritchie01/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true scottritchie01/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-test"
  env: "docker-test-env"
  bucket-name: "elasticbeanstalk-us-east-2-540086156761"
  bucket-path: "docker-react"
  on:
    branch: master
